### ISSUE TITLE
New ynab-bank-importer version not getting ING-DiBa "Payee"

### ISSUE THREAD

**Issue by quifago** [schurig/ynab-bank-importer#13]
Hi, 

With the new version (using YNAB access_token), my transactions from ING-DiBa do not have anymore the 'Payee' field as before. 

Let me know if I can help you with some logs, or try to debug the code... Unfortunately I'm not seeing anymore the CSV files within the 'export' folder as before to try to provide you with more details.

Also, big thanks for this project!!!

**Comment by quifago** [comment]
In case this helps, I was able to print in the console some transaction details info from the fints.rb adaptor:

This is an example of a transfer in Ikea, and these are the values I printed:
```
      puts("DETAILS: #{transaction.details.source}")
      puts("PAYEE: #{payee_name(transaction)}")
      puts("AMOUNT: #{transaction.amount}")
```

```
DETAILS: 005?00Lastschrifteinzug?10009500?20SVWZ+NR8194366016 TAUFKIRCH?21ENKAUFUMSATZ11.08190207ARN7?224830728223312300079008?32VISA IKEADEUTSCHLAND NL BR?33
PAYEE: VISA IKEADEUTSCHLAND NL BR
AMOUNT: 179.35
-----
```

So, everything looks ok in the dumper... 

I printed some other values in the transaction_creator.rb

```
def call(options = {})
    
      puts("PAYEE ID: #{payee_id(options)}")
      puts("PAYEE: #{payee_name(options)}")
      puts("AMOUNT: #{options.fetch(:amount)}")
      puts("------")
      YNAB::SaveTransaction.new(
```

```
PAYEE ID:
PAYEE: VISA IKEADEUTSCHLAND NL BR
AMOUNT: -179350
------
```

So, here also looks right... 
But when I see the transaction in YNAB app, this is what I see:
![screen shot 2018-08-16 at 08 45 04](https://user-images.githubusercontent.com/2972550/44192691-b7dcc080-a130-11e8-89e8-a18b33f9974e.png)

I don't know where else to look, but I would be glad to help in case someone can point me to another part of the code.

**Comment by schurig** [comment]
I just debugged on my machine and it seems to work properly. It sets the `payee_id` to a null value. 


![screen_shot_2018-08-16_at_19_39_42](https://user-images.githubusercontent.com/2672413/44224900-3f0b5200-a18c-11e8-8148-e4a6fd524d14.jpg)


What I noticed the other day is that in YNAB under Payees there was an empty string with some rules. I couldn't explain how that happened (maybe they messed something up on their side). If that's also the case for you, try deleting it.

**Comment by quifago** [comment]
Hi,
This is what I get for the 'internal_account_id':
```
PAYEE ID:
PAYEE: VISA IKEADEUTSCHLAND NL BR
AMOUNT: -179350
INTERNAL ACC ID:
------
```

Also, I checked and I don't have an 'empty' payee item in the Manage Payees table. 
I created a new budget (of course with no payees in YNAB), imported again the transactions and had the same result... 

I wish I could help you more, but I don't know enough Ruby to 'really' debug this code end to end...

**Comment by schurig** [comment]
@quifago I just had a credit card transaction on my ING-DiBa account and for me it worked: 
![screen shot 2018-08-18 at 11 46 37](https://user-images.githubusercontent.com/2672413/44298053-83a60300-a2dc-11e8-9c48-882b62774d98.jpg)

I'm using the latest version (latest commit on master) on my raspberry pi that runs the script every 15 minutes via a cronjob. Very strange that it don't work for you. You're also using the credit card or are all those expenses done using the Maestro? Maybe it somehow is different in that case 🤔

**Comment by quifago** [comment]
That's weird... today it worked! 

I created a new budget and I have imported successfully all the transactions there.
I run the importer again pointing to my 'official' budget ID in YNAB and imported successfully 2 new transactions from last days. 
So, it seems that magically, the problem have been solved 😄 

Is there any way now to delete the transactions without payee in YNAB and that the importer uploads them again? do you (or YNAB) have any cache that I can clear to re-import them?

Thanks for your support

**Comment by schurig** [comment]
Glad to hear it works now! 🎉

Unfortunately I don't know of any way how you could reimport the empty ones because I generate a `import_id` based on some values and if they don't change then YNAB will consider that transaction as already imported (even if you deleted it) - that's how their API manages to not reimport already imported transactions - do it's actually a feature.

What you could do is to download the transactions as .csv on the ING-DiBa website, change it to the YNAB import csv layout and then upload it through the web-app: https://docs.youneedabudget.com/article/921-importing-a-csv-file
