### ISSUE TITLE
Undefined method `categories'

### ISSUE THREAD

**Issue by peterjeschke** [schurig/ynab-bank-importer#23]
I just tried the importer and wanted to import my n26 data into ynab. I installed docker, configured it and run it. But instead of importing my data, it threw an exception:

```
Traceback (most recent call last):
        5: from /usr/app/run.rb:9:in `<main>'
        4: from /usr/app/run.rb:9:in `map'
        3: from /usr/app/run.rb:11:in `block in <main>'
        2: from /usr/app/lib/account.rb:18:in `fetch_transactions'
        1: from /usr/app/lib/dumper/n26.rb:25:in `fetch_transactions'
/usr/local/bundle/gems/httparty-0.16.0/lib/httparty/response.rb:101:in `method_missing': undefined method `categories' for #<HTTParty::Response:0x00005622236033f8> (NoMethodError)

```

**Comment by schurig** [comment]
Hi @peterjeschke, can you please double-check your n26 credentials? I was able to reproduce this by using wrong N26 credentials.

**Comment by schurig** [comment]
I just merged a PR that should show a better error message in case that happens (#24). So if you pull the latest version from the docker-registry you should now see a better error message.

`docker-compose pull importer`
`docker-compose run importer`

**Comment by peterjeschke** [comment]
Yes! Thank you for your help and thank you for the new error message,
that's awesome!

Martin Schurig <notifications@github.com> schrieb am Mo., 17. Sep. 2018 um
10:13 Uhr:
