### ISSUE TITLE
N26 importer creates duplicate entries

### ISSUE THREAD

**Issue by peterjeschke** [schurig/ynab-bank-importer#36]
I still couldn't pinpoint the exact source for this problem, but maybe someone more insight into this issue. Sometimes, the n26 importer creates duplicate transactions of already existing transactions. At first, only one transaction is shown (that is correct) but after running the importer a few times, a second transaction is created. This happens frequently with relatively recent transactions, but a few days ago, it happened with transactions that were three months old. It doesn't happen with every transaction either.

My hunch is that n26 changes the payee and memo fields, but I couldn't pinpoint it exactly. I have attached one instance of the duplicated transation: 

![image](https://user-images.githubusercontent.com/614673/47915372-f453c900-dea2-11e8-9757-51c868b278cd.png)

**Comment by schurig** [comment]
Hi Peter, I’m also facing this issue and I find it a bit frustrating. The reason for it is the YNAB api which changes the timestamp by a few milliseconds. That means that their data is inconsitend. The change happens when a transaction gets processed.

The only solution I can think of is to add an option to the N26 dumper to not import not-processed transactions. That would mean that if you pay something today it might be imported during the next 2-3 days. Would that work for you?

**Comment by peterjeschke** [comment]
I don't I understand what you mean by transation processing. How does YNAB process these transactions and why does it only affect N26? Or does the n26 api changes the timestamp?

**Comment by schurig** [comment]
Yes correct the N26 api changed the timestamp. They have a timezone mismatch which I already handle but they also sometimes change the seconds/milliseconds which I can’t handle

**Comment by manuelgrabowski** [comment]
I had the same issue. Reading this discussion, my first thought was that it might be worth using only "HH:mm" from the timestamp for the hash… I guess it would be pretty rare to have two transactions in the same minute with the same amount (I'm only guessing the amount is part of the hash, though). But as you wrote, even "rounding" to "HH:mm" could still result in deviations, so it's not perfect either. Has N26 ever commented on their shitty API output? Don't they have a unique identifier for each transaction in their API output?

**Comment by manuelgrabowski** [comment]
That PSD2 thing sounds interesting, neat! I agree with your reasoning about the default value for the new flag, and apart from the small typo I found the PR looks great to me! 🎉
