### ISSUE TITLE
UTF-8 conversion error

### ISSUE THREAD

**Issue by peterjeschke** [schurig/ynab-bank-importer#39]
Since a few days, all my imports failed because the importer failed with this exception:

```
Traceback (most recent call last):
        10: from run.rb:9:in `<main>'
         9: from run.rb:9:in `map'
         8: from run.rb:11:in `block in <main>'
         7: from /home/pi/ynab-bank-importer/lib/account.rb:18:in `fetch_transactions'
         6: from /home/pi/ynab-bank-importer/lib/dumper/fints.rb:24:in `fetch_transactions'
         5: from /home/pi/ynab-bank-importer/lib/dumper/fints.rb:24:in `map'
         4: from /home/pi/ynab-bank-importer/lib/dumper/fints.rb:24:in `block in fetch_transactions'
         3: from /home/pi/ynab-bank-importer/lib/dumper.rb:30:in `to_ynab_transaction'
         2: from /home/pi/ynab-bank-importer/lib/dumper/fints.rb:68:in `import_id'
         1: from /home/pi/ynab-bank-importer/lib/dumper/fints.rb:88:in `transaction_type'
/home/pi/ynab-bank-importer/lib/dumper/fints.rb:88:in `encode': U+CC44 from UTF-8 to ISO-8859-1 (Encoding::UndefinedConversionError)
```

The U+CC44 seems to be a korean sign:

> 채 U+CC44 HANGUL SYLLABLE CAE, decimal: 52292, HTML: &#52292;, UTF-8: 0xEC 0xB1 0x84, block: Hangul Syllables, decomposition: U+110E U+1162

I narrowed it down to a single account and I think I know the culprit: one transaction contains an umlaut (in this case ä). There are actually three not-yet-imported transactions, so I can't be certain.

This is an ING "Extra-Konto" for savings, and the three transactions are system-transactions, not normal transactions.

I'm not sure whether fints even allows unicode, so I'm reluctant to just change the code in question.

**Comment by schurig** [comment]
I bet it was the `Solidaritätszuschlag`. Someone else reached out to me about the same problem (also ING-DiBa). I just had a look and for me it worked fine.

Would you mind adding two small lines of code before the following:

https://github.com/schurig/ynab-bank-importer/blob/dcfc54011fa62dd2add8b4c23aac3637f2a11705/lib/dumper/fints.rb#L88-L89

Before line `88` it would help me if you could add:

```ruby
puts str
puts str.inspect
```

I would love to see what the output just before the error happens looks like. I guess that the encoding is already in `utf-8`. So I might add a rescue block in there.
