### ISSUE TITLE
multiple budgets?

### ISSUE THREAD

**Issue by deyhle** [schurig/ynab-bank-importer#42]
Is it possible to configure multiple budgets? So, Budget A with Bank Account 1 and 2, Budget B with Bank Account 3 and 4? Both Budgets belong to the same YNAB Account.

**Comment by schurig** [comment]
Hi @deyhle, currently the script doesn't support multiple budgets. But if you're using docker you could create two different directories (they should be named differently) and let the script run in two instances. This should work I think. Let me know if it works in case you want to give it a try.
