### ISSUE TITLE
NoMethodError with FINTS (Deutsche Bank)

### ISSUE THREAD

**Issue by misterfinster** [schurig/ynab-bank-importer#59]
Love the project, have been using it for a few months.  I use the FINTS importer.  About 7 days ago, my import (I run it nightly via cron with docker-compose run) stopped importing.  Not sure if it is related to Merge #57 or Merge #56 but this is the traceback I get now after updating everything (git repo, docker image, etc):

Traceback (most recent call last):
	7: from /usr/app/run.rb:9:in `<main>'
	6: from /usr/app/run.rb:9:in `map'
	5: from /usr/app/run.rb:11:in `block in <main>'
	4: from /usr/app/lib/account.rb:18:in `fetch_transactions'
	3: from /usr/app/lib/dumper/fints.rb:24:in `fetch_transactions'
	2: from /usr/app/lib/dumper/fints.rb:24:in `map'
	1: from /usr/app/lib/dumper/fints.rb:24:in `block in fetch_transactions'
/usr/app/lib/dumper.rb:19:in `to_ynab_transaction': undefined method `>' for nil:NilClass (NoMethodError)

**Comment by schurig** [comment]
Hi @misterfinster, thanks for opening this issue. Sorry to hear that the script broke for you. Working with so many banks is always tricky. I just merged something that hopefully fixes your problem.

Can you give it a try?

You might need to pull the latest image from the docker-registry:

`docker-compose pull` and then run the script again.

**Comment by misterfinster** [comment]
After enabling debugging as described in issue #22 I think I see what the real deal is with my transactions.  In Deutsche Bank, they use the concept of 'queued' transactions.  The first 'queued' transaction (my rent payment) has far fewer fields than a cleared transaction.

**Comment by misterfinster** [comment]
In the cleared transaction, there are date fields in the `@data` structure like this:
`@data={"date"=>"190401", "entry_date"=>nil, ..... }`
but in the 'queued' transaction, the first `@data` field is empty and there are no 'date' fields:
`@data={}`

**Comment by schurig** [comment]
This is the first time I've heard that a bank also provides this information. Would it be okay for you if I just ignore all transactions that don't have a date? Because in the end as soon as your rent is processed it, it would show up as a regular transaction

**Comment by misterfinster** [comment]
Yeah, ignoring  sounds like a decent solution to me.  I usually already have a transaction entered (scheduled or manual) and just match up the auto-imported ones when I reconcile.  Thanks for the quick responses.
