### ISSUE TITLE
endpoint for targobank?

### ISSUE THREAD

**Issue by gingerlime** [schurig/ynab-bank-importer#62]
Hi there,

I'm hitting my head against the wall on this one, trying to find the fints endpoint for Targobank (BLZ 30020900)... I think Targo only introduced it recently, so maybe that's why it's nowhere to be found. Would appreciate any help on this one :)

side note : isn't the whole point of HBCI to open up banking?? but then those endpoints are some kind of a secret, I don't quite understand it... ;-)

**Comment by schurig** [comment]
Hi @gingerlime, can you try it with https://fints.targobank.de/travicretail_fints30pintanbroker/FinTs30PinTanHttpGate?

I agree with what you said. A year ago the list was still public. I don't get why they went this path. I already wrote them an email about it some time ago but they only pointed me to the registration: https://www.hbci-zka.de/register/hersteller.htm

**Comment by gingerlime** [comment]
Thanks @schurig. It looks like this endpoint responds, but somehow I'm getting a 403 with the right credentials... 

I'm using python-fints to test this (which the ruby implementation was based on)

```python
>>> from fints.client import FinTS3PinTanClient
>>> f = FinTS3PinTanClient('30020900', myuser, mypass, 'https://fints.targobank.de/travicretail_fints30pintanbroker/FinTs30PinTanHttpGate')
>>> f.get_sepa_accounts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/client.py", line 414, in get_sepa_accounts
    with self._get_dialog() as dialog:
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/client.py", line 254, in _get_dialog
    self._ensure_system_id()
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/client.py", line 1053, in _ensure_system_id
    HKSYN3(SynchronizationMode.NEW_SYSTEM_ID),
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/dialog.py", line 72, in init
    retval = self.send(*segments, internal_send=True)
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/dialog.py", line 114, in send
    response = self.client.connection.send(message)
  File "/Users/***/.pyenv/versions/fints/lib/python3.7/site-packages/fints/connection.py", line 30, in send
    raise FinTSConnectionError('Bad status code {}'.format(r.status_code))
fints.exceptions.FinTSConnectionError: Bad status code 403
```

Having no problems with ING Diba though ... I guess it's those kind of things that would be impossible to debug unless I knew someone at the development team of the bank responsible for it, but otherwise nobody can really help :(

Anyway, thanks a lot for the link. I really appreciate it.

**Comment by gingerlime** [comment]
Very strange. `ruby_fints` seems to work fine. No clue why it fails with python with the exact same details. Possibly some unicode/character encoding issue? In any case, this is the correct endpoint for Targobank. Thanks again @schurig !

In case it helps anyone, I also found this [database of fints endpoints](https://raw.githubusercontent.com/jhermsmeier/fints-institute-db/master/fints-institutes.json)
