### ISSUE TITLE
Suggestion for Wiki

### ISSUE THREAD

**Issue by felixwoestmann** [schurig/ynab-bank-importer#66]
Hello there,
I just tested the script with my Account at Volksbank (Gronau-Ahaus).
It is necessary to use the 'pinTanURL'.

Maybe you want to add this to "Currently tested with:" in the Wiki.

**Comment by schurig** [comment]
Hey @felixwoestmann, thanks for the info 😊

I just added it https://github.com/schurig/ynab-bank-importer/wiki/FinTS---HBCI
