### ISSUE TITLE
Can not authenticate with n26 api

### ISSUE THREAD

**Issue by theTranqu** [schurig/ynab-bank-importer#67]
```
 pi@raspberrypi:~/ynab-bank-importer $ sudo docker-compose run importer
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to api.tech26.de:443 (getaddrinfo: Nameor service not known) (SocketError)
        from /usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
        from /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
        from /usr/local/lib/ruby/2.4.0/net/http.rb:1407:in `request'
        from /usr/local/bundle/gems/httparty-0.16.3/lib/httparty/request.rb:145:in `perform'
        from /usr/local/bundle/gems/httparty-0.16.3/lib/httparty.rb:573:in `perform_request'
        from /usr/local/bundle/gems/httparty-0.16.3/lib/httparty.rb:507:in `post'
        from /usr/local/bundle/gems/twentysix-0.1.1/lib/twentysix/core.rb:9:in `authenticate'
        from /usr/app/lib/dumper/n26.rb:26:in `fetch_transactions'
        from /usr/app/lib/account.rb:18:in `fetch_transactions'
        from /usr/app/run.rb:11:in `block in <main>'
        from /usr/app/run.rb:9:in `map'
        from /usr/app/run.rb:9:in `<main>'

```

I am running the importer on my raspberry pi with docker-compose. At some point some two weeks ago, the import process just stopped working. I have not changed the password and I have confirmed that the correct password is set in the config.

I have also confirmed that I can connect to the api.tech26.de:443:
```
pi@raspberrypi:~/ynab-bank-importer $ curl https://api.tech26.de
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
```

Does anyone else experience similar problems?
Did something on the n26 api change?
Not being to authenticate _anymore_ , even though it worked before and nothing changed on my side of the authentication is somewhat confusing.

How can I help with debugging?

**Comment by schurig** [comment]
Hi @theTranqu, I'm using N26 myself and for me the import still works. Did something to your docker setup change lately? It's indeed weird that on the raspberry pi you can run a curl successfully but the script isn't able to connect.

**Comment by theTranqu** [comment]
@schurig Thank you for your response, I am sorry to drop in a false alarm here. Apparently _something_ was wrong with docker- nothing had changed and the daemon was still responding, but it failed to open tcp connections. Doing a stop of the docker service including a removal of all the /var/lib/docker and /var/run/docker and /var/run/docker.* files and a subsequent restart of docker cleaned up the problem for me.
Thank you for pointing me in the right direction and the work on the importer!
