### ISSUE TITLE
Consider using the new YNAB API?

### ISSUE THREAD

**Issue by bradymholt** [schurig/ynab-bank-importer#8]
Hi @schurig, I'm a developer at YNAB.  This project looks nice!  I wanted to let you know we are working on an REST based API which is currently in Early Access stage.  I'm hoping you would be interested in joining and evaluating usage of the API for this project.  We support creating transactions through the API and will be rolling out an update this week which provides first-class handling for imported transactions.  If you're interested, please fill out this quick survey: https://goo.gl/forms/TL87uGCl0tUAayD72 and then we can get in in the Early Access group.

**Comment by schurig** [comment]
Hey @bradymholt, thank you very much for reaching out to me. I just requested access to try it asap. If it works well, I can finally dump the selenium webdriver import and replace it with something very light that can run regularly on small devices like a raspberry pi.

**Comment by bradymholt** [comment]
Great!  We'll reach out to you soon with some instructions.
