### ISSUE TITLE
Unclear about cash_account_id

### ISSUE THREAD

**Issue by simonszu** [schurig/ynab-bank-importer#80]
I am a little unsure about the cash_account_id. I understand the documentation that it defines the actual cash account, so when it detects a transfer to cash on my main account, it will automatically create a "transfer to cash" action in YNAB. 

But if i have multiple accounts on different banks in the same budget (type "Checking), and only one cash account (type "Cash"), why should i specify the cash_account_id? And how will the script detect which account in YNAB it is linked to? Or is the name "cash" misleading and you are not referring to actual cash, like coins and notes, but to the account the script should import to?

**Comment by simonszu** [comment]
Nevermind, i haven't seen the `ynab_id` setting later in the config yet.

**Comment by gitviola** [comment]
Hey @simonszu, yes exactly, the term `cash` in this specific setting refers to the physical cash you might store at home/wallet in your pocket. So the script basically matches for terms like ATM, Geldautomat, ... to detect cash withdrawals and then it creates a transaction from the account the money was taken from to the ynab account id that you provided in that setting.
