### ISSUE TITLE
"Automate it" - small typo in cron command

### ISSUE THREAD

**Issue by simonszu** [schurig/ynab-bank-importer#81]
I have just set up the importer and noticed a small typo in the cron command described in the Wiki. It says `cd /home/youruser/.ynab-bank-importer && /usr/local/bin/docker-compose run --rm importer | mail -s "YNAB importer failed" youremail@example.com`.

Based on the mail subject line i see that the mail should be sent when the importer fails. But currently it is sent everytime, since the output of the docker-compose command (which is none) is just piped into the mail command. You shold fix it and write a double-pipe instead which is evaluated as an OR. After that the command is evaluated like it should: Execute docker-command until success OR write a mail to notify the user.

**Comment by gitviola** [comment]
Thanks a lot @simonszu! I just corrected it on those wiki pages:

https://github.com/schurig/ynab-bank-importer/wiki/Setup-using-docker
https://github.com/schurig/ynab-bank-importer/wiki/Raspberry-PI-using-Docker
https://github.com/schurig/ynab-bank-importer/wiki/Raspberry-PI-without-docker
